Vagrant.configure("2") do |config|
  config.vm.define "ubuntu-curso-linux" do |debian|
    debian.vm.box = "ubuntu/focal64"
    debian.vm.hostname = "ubuntu-curso-linux"
    debian.vm.network "private_network", ip: "192.168.33.12"
    debian.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-curso-linux"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end