Vagrant.configure("2") do |config|
    config.vm.define "kali-curso-linux" do |kali|
      kali.vm.box = "kalilinux/rolling"
      kali.vm.hostname = "kali-curso-linux"
      kali.vm.network "private_network", ip: "192.168.33.15"
      kali.vm.provider "virtualbox" do |vb|
        vb.name = "kali-curso-linux"
        vb.memory = "2048"
        vb.cpus = 2
      end
    end
  end