Vagrant.configure("2") do |config|
  config.vm.define "debian-curso-linux" do |debian|
    debian.vm.box = "debian/buster64"
    debian.vm.hostname = "debian-curso-linux"
    debian.vm.network "private_network", ip: "192.168.33.10"
    debian.vm.provider "virtualbox" do |vb|
      vb.name = "debian-curso-linux"
      vb.memory = "2048"
      vb.cpus = 2
    end
    debian.vm.provision "shell", inline: "apt-get update && apt-get install -y openssl"
  end
end